<?php

/** @var yii\web\View $this */

$this->title = 'TC Olching Teams';
?>

<div class="site-index">
    <div class="body-content">
        <div class="container">

            <div class="row">
                <article id="inhalt" class="col content-table">
                    <!-- Content Table generated by JavaScript -->
                </article>
            </div>

            <div class="row">
                <article id="mannschaften" class="col">
                    <header>
                        <h2>Die Mannschaften des TC Olching</h2>
                    </header>
                    <a href="https://www.btv.de/de/mein-verein/vereinsseite/tc-olching.html#Mannschaften">Die Mannschaften des TC Olching beim BTV</a>
                    <h2>Links zu wichtigen Tennisregeln, Wenn es mal zu Diskussionen kommt</h2>
                    <ul>
                        <li><a href="https://www.btv.de/dam/jcr:2b0c670b-2ecd-4b1f-9564-f4f39a0f7e0d/btv_regeln_2022_IV_wettspielbestimmungen%20btv.pdf"> Die Durchführungsbestimmungen 2022</a></li>
                        <li><a href="https://www.btv.de/de/der-btv/ueber-den-btv/regeln-und-ordnungen.html">Regeln / Ordnungen 2022 (BTV)</a></li>
                        <li><a href="http://www.dtb-tennis.de/content/download/680/8523/version/3/file/Tennisregeln.pdf">Tennisregeln (ITF)</a></li>
                    </ul>
                    </section>
                </article>
            </div>
            <div class="row">
                <article id="platzbelegung" class="col">
                    <header>
                        <h2>Platzbelegung Sommer 2023</h2>
                    </header>
                    <p>Der TC Olching verfügt über 6 Sandplätze.</p>
                    <p><strong>BITTE BEACHTE</strong>, dass während der Punktspielzeit die Plätze an vielen Wochenenden belegt sind. Die Platzbelegungen des Mannschaftstrainings und des Vereinstrainers findest du im folgenden Plan. Die Mannschaftstrainings gelten ganzjährig.</p>
                    <p><strong>ACHTUNG:</strong> Ein Spielender darf kein Clubturnier-Match spielen, während sein Mannschaftstraining stattfindet!</p>
                    <img class="img-fluid" src="img/misc/trainingsplan_2023.png" alt="Platzbelegung">
                </article>
            </div>


            <div class="row">
                <article id="spielplan" class="col">
                    <header>
                        <h2>Die Spiele des TC Olching in 2023</h2>
                    </header>
                    <p>
                        Zusätzlich zu den Trainingszeiten gibt es Platzbelegungen an Wochenenden und Feiertagen. Eine Begegnung dauert durchschnittlich 5 Stunden, also von 09:00 bis 14:00 Uhr oder von 14 Uhr bis 19 Uhr, kann sich aber auch länger ziehen. Eine 6er-Mannschaft belegt i. d. R. immer mindestens 3 Plätze, eine 4er-Mannschaft mindestens 2. Hier sind die Spieltermine:
                    </p>


                    <table class="tco-table tco-tbl-small">
                        <thead>
                            <tr>
                                <th> Termin </th>
                                <th> Liga </th>
                                <th> Heimmannschaft </th>
                                <th> Gastmannschaft </th>
                            </tr>
                        </thead>
                        <tr>
                            <td align="right"> Fr. 05.05.2023 15:00 </td>
                            <td> S3 </td>
                            <td> TSV Eintracht Karlsfeld </td>
                            <td> <strong> Mädchen 15 (4er) </strong> </td>
                        </tr>
                        <tr>
                            <td align="right"> Sa. 06.05.2023 09:00 </td>
                            <td> S3 </td>
                            <td> <strong> Junioren 18 (4er) </strong> </td>
                            <td> TC Dachau 1950 II </td>
                        </tr>
                        <tr>
                            <td align="right"> 09:00 </td>
                            <td> S4 </td>
                            <td> <strong> Junioren 18 II (4er) </strong> </td>
                            <td> TC Eichenau II </td>
                        </tr>
                        <tr>
                            <td align="right"> 14:00 </td>
                            <td> LL2 </td>
                            <td> <strong> Damen 40 </strong> </td>
                            <td> TCE Gröbenzell </td>
                        </tr>
                        <tr>
                            <td align="right"> 14:00 </td>
                            <td> S4 </td>
                            <td> TC Puchheim II </td>
                            <td> <strong> Herren 30 (4er) </strong> </td>
                        </tr>
                        <tr>
                            <td align="right"> 14:00 </td>
                            <td> S1 </td>
                            <td> TC Augsburg Siebentisch </td>
                            <td> <strong> Herren 40 </strong> </td>
                        </tr>
                        <tr>
                            <td align="right"> 14:00 </td>
                            <td> S3 </td>
                            <td> <strong> Herren 50 II </strong> </td>
                            <td> TSV Deuringen </td>
                        </tr>
                        <tr>
                            <td align="right"> 14:00 </td>
                            <td> S1 </td>
                            <td> SV Söcking </td>
                            <td> <strong> Herren 55 (5er) </strong> </td>
                        </tr>
                        <tr>
                            <td align="right"> 14:00 </td>
                            <td> S1 </td>
                            <td> SC Oberweikertshofen </td>
                            <td> <strong> Damen 50 (4er) </strong> </td>
                        </tr>
                        <tr>
                            <td align="right"> So. 07.05.2023 09:00 </td>
                            <td> S4 </td>
                            <td> TG Germerswang </td>
                            <td> <strong> Herren </strong> </td>
                        </tr>
                        <tr>
                            <td align="right"> 09:00 </td>
                            <td> S3 </td>
                            <td> TC Gernlinden II </td>
                            <td> <strong> Damen </strong> </td>
                        </tr>
                        <tr>
                            <td align="right"> 10:00 </td>
                            <td> LL2 </td>
                            <td> <strong> Herren 50 </strong> </td>
                            <td> TCE Gröbenzell </td>
                        </tr>
                        <tr>
                            <td align="right"> 15:00 </td>
                            <td> S2 </td>
                            <td> <strong> Dunlop Midcourt U10 (4er) </strong> </td>
                            <td> TF Dachau </td>
                        </tr>
                        <tr>
                            <td align="right"> Mo. 08.05.2023 10:00 </td>
                            <td> S1 </td>
                            <td> <strong> Freizeit-Damen Doppel 60 </strong> </td>
                            <td> TC Utting </td>
                        </tr>
                        <tr>
                            <td align="right"> Fr. 12.05.2023 15:00 </td>
                            <td> S5 </td>
                            <td> TG Germerswang </td>
                            <td> <strong> Knaben 15 (4er) </strong> </td>
                        </tr>
                        <tr>
                            <td align="right"> 15:00 </td>
                            <td> S3 </td>
                            <td> <strong> Mädchen 15 (4er) </strong> </td>
                            <td> SV Stadtwerke München </td>
                        </tr>
                        <tr>
                            <td align="right"> Sa. 13.05.2023 09:00 </td>
                            <td> S3 </td>
                            <td> TG Germerswang </td>
                            <td> <strong> Junioren 18 (4er) </strong> </td>
                        </tr>
                        <tr>
                            <td align="right"> 09:00 </td>
                            <td> S4 </td>
                            <td> TSV Geiselbullach </td>
                            <td> <strong> Junioren 18 II (4er) </strong> </td>
                        </tr>
                        <tr>
                            <td align="right"> 09:00 </td>
                            <td> S3 </td>
                            <td> TF Dachau </td>
                            <td> <strong> Bambini 12 (4er) </strong> </td>
                        </tr>
                        <tr>
                            <td align="right"> 14:00 </td>
                            <td> LL2 </td>
                            <td> TSV Schwabmünchen </td>
                            <td> <strong> Herren 50 </strong> </td>
                        </tr>
                        <tr>
                            <td align="right"> 14:00 </td>
                            <td> S4 </td>
                            <td> TSC WWK </td>
                            <td> <strong> Herren 30 (4er) </strong> </td>
                        </tr>
                        <tr>
                            <td align="right"> 14:00 </td>
                            <td> S1 </td>
                            <td> <strong> Herren 40 </strong> </td>
                            <td> BC Schretzheim </td>
                        </tr>
                        <tr>
                            <td align="right"> 14:00 </td>
                            <td> S3 </td>
                            <td> TC Friedberg III </td>
                            <td> <strong> Herren 50 II </strong> </td>
                        </tr>
                        <tr>
                            <td align="right"> 14:00 </td>
                            <td> S1 </td>
                            <td> <strong> Herren 55 (5er) </strong> </td>
                            <td> TP Starnberg 1987 </td>
                        </tr>
                        <tr>
                            <td align="right"> 14:00 </td>
                            <td> S1 </td>
                            <td> SpVgg Erdweg II </td>
                            <td> <strong> Damen 50 (4er) </strong> </td>
                        </tr>
                        <tr>
                            <td align="right"> So. 14.05.2023 09:00 </td>
                            <td> S4 </td>
                            <td> <strong> Herren </strong> </td>
                            <td> TF Dachau II </td>
                        </tr>
                        <tr>
                            <td align="right"> 09:00 </td>
                            <td> S3 </td>
                            <td> 1. SC Gröbenzell </td>
                            <td> <strong> Damen </strong> </td>
                        </tr>
                        <tr>
                            <td align="right"> 10:00 </td>
                            <td> LL2 </td>
                            <td> TC Blutenburg München </td>
                            <td> <strong> Damen 40 </strong> </td>
                        </tr>
                        <tr>
                            <td align="right"> 15:00 </td>
                            <td> S2 </td>
                            <td> TSV Eintracht Karlsfeld </td>
                            <td> <strong> Dunlop Midcourt U10 (4er) </strong> </td>
                        </tr>
                        <tr>
                            <td align="right"> Mo. 15.05.2023 10:00 </td>
                            <td> S1 </td>
                            <td> 1. SC Gröbenzell </td>
                            <td> <strong> Freizeit-Damen Doppel 60 </strong> </td>
                        </tr>
                        <tr>
                            <td align="right"> Fr. 19.05.2023 15:00 </td>
                            <td> S5 </td>
                            <td> <strong> Knaben 15 (4er) </strong> </td>
                            <td> TC Gernlinden IV </td>
                        </tr>
                        <tr>
                            <td align="right"> Sa. 20.05.2023 09:00 </td>
                            <td> S4 </td>
                            <td> <strong> Junioren 18 II (4er) </strong> </td>
                            <td> TCE Gröbenzell II </td>
                        </tr>
                        <tr>
                            <td align="right"> 09:00 </td>
                            <td> S3 </td>
                            <td> TF Dachau III </td>
                            <td> <strong> Mädchen 15 (4er) </strong> </td>
                        </tr>
                        <tr>
                            <td align="right"> 14:00 </td>
                            <td> LL2 </td>
                            <td> TC Rot-Weiß Krumbach </td>
                            <td> <strong> Herren 50 </strong> </td>
                        </tr>
                        <tr>
                            <td align="right"> 14:00 </td>
                            <td> LL2 </td>
                            <td> <strong> Damen 40 </strong> </td>
                            <td> TC Tutzing </td>
                        </tr>
                        <tr>
                            <td align="right"> 14:00 </td>
                            <td> S4 </td>
                            <td> <strong> Herren 30 (4er) </strong> </td>
                            <td> SC Mühlried </td>
                        </tr>
                        <tr>
                            <td align="right"> 14:00 </td>
                            <td> S1 </td>
                            <td> TeG Rothtal </td>
                            <td> <strong> Herren 40 </strong> </td>
                        </tr>
                        <tr>
                            <td align="right"> </td>
                            <td> 0 </td>
                            <td> Spielort: SpVgg Auerbach-... </td>
                            <td> 0 </td>
                        </tr>
                        <tr>
                            <td align="right"> 14:00 </td>
                            <td> S3 </td>
                            <td> TSV Bergkirchen </td>
                            <td> <strong> Herren 50 II </strong> </td>
                        </tr>
                        <tr>
                            <td align="right"> 14:00 </td>
                            <td> S1 </td>
                            <td> TSC WWK </td>
                            <td> <strong> Herren 55 (5er) </strong> </td>
                        </tr>
                        <tr>
                            <td align="right"> So. 21.05.2023 09:00 </td>
                            <td> S4 </td>
                            <td> TC Karlsfeld am See </td>
                            <td> <strong> Herren </strong> </td>
                        </tr>
                        <tr>
                            <td align="right"> 09:00 </td>
                            <td> S3 </td>
                            <td> <strong> Damen </strong> </td>
                            <td> MTV 1879 München </td>
                        </tr>
                        <tr>
                            <td align="right"> 09:00 </td>
                            <td> S1 </td>
                            <td> <strong> Damen 50 (4er) </strong> </td>
                            <td> TC Mering </td>
                        </tr>
                        <tr>
                            <td align="right"> 15:00 </td>
                            <td> S2 </td>
                            <td> SV Petershausen </td>
                            <td> <strong> Dunlop Midcourt U10 (4er) </strong> </td>
                        </tr>
                        <tr>
                            <td align="right"> Mo. 22.05.2023 10:00 </td>
                            <td> S1 </td>
                            <td> TC Gernlinden </td>
                            <td> <strong> Freizeit-Damen Doppel 60 </strong> </td>
                        </tr>
                        <tr>
                            <td align="right"> Mo. 12.06.2023 10:00 </td>
                            <td> S1 </td>
                            <td> <strong> Freizeit-Damen Doppel 60 </strong> </td>
                            <td> TCE Gröbenzell </td>
                        </tr>
                        <tr>
                            <td align="right"> Fr. 16.06.2023 15:00 </td>
                            <td> S5 </td>
                            <td> <strong> Knaben 15 (4er) </strong> </td>
                            <td> VfL Egenburg </td>
                        </tr>
                        <tr>
                            <td align="right"> Sa. 17.06.2023 09:00 </td>
                            <td> S3 </td>
                            <td> <strong> Junioren 18 (4er) </strong> </td>
                            <td> TC Gernlinden </td>
                        </tr>
                        <tr>
                            <td align="right"> 09:00 </td>
                            <td> S3 </td>
                            <td> <strong> Bambini 12 (4er) </strong> </td>
                            <td> TC Blutenburg München II </td>
                        </tr>
                        <tr>
                            <td align="right"> 09:00 </td>
                            <td> S4 </td>
                            <td> TC Fürstenfeldbruck </td>
                            <td> <strong> Junioren 18 II (4er) </strong> </td>
                        </tr>
                        <tr>
                            <td align="right"> 14:00 </td>
                            <td> LL2 </td>
                            <td> <strong> Herren 50 </strong> </td>
                            <td> TC Friedberg II </td>
                        </tr>
                        <tr>
                            <td align="right"> 14:00 </td>
                            <td> S3 </td>
                            <td> <strong> Herren 50 II </strong> </td>
                            <td> SV Sulzemoos </td>
                        </tr>
                        <tr>
                            <td align="right"> So. 18.06.2023 09:00 </td>
                            <td> S3 </td>
                            <td> <strong> Damen </strong> </td>
                            <td> TCE Gröbenzell </td>
                        </tr>
                        <tr>
                            <td align="right"> 09:00 </td>
                            <td> S4 </td>
                            <td> TC Gerolsbach </td>
                            <td> <strong> Herren 30 (4er) </strong> </td>
                        </tr>
                        <tr>
                            <td align="right"> 14:00 </td>
                            <td> S1 </td>
                            <td> TC Gernlinden II </td>
                            <td> <strong> Herren 55 (5er) </strong> </td>
                        </tr>
                        <tr>
                            <td align="right"> Fr. 23.06.2023 15:00 </td>
                            <td> S3 </td>
                            <td> <strong> Mädchen 15 (4er) </strong> </td>
                            <td> TSV Moosach München </td>
                        </tr>
                        <tr>
                            <td align="right"> Sa. 24.06.2023 09:00 </td>
                            <td> S3 </td>
                            <td> Münchner Sportclub II </td>
                            <td> <strong> Junioren 18 (4er) </strong> </td>
                        </tr>
                        <tr>
                            <td align="right"> 09:00 </td>
                            <td> S3 </td>
                            <td> <strong> Bambini 12 (4er) </strong> </td>
                            <td> TC Puchheim </td>
                        </tr>
                        <tr>
                            <td align="right"> 09:00 </td>
                            <td> S4 </td>
                            <td> <strong> Junioren 18 II (4er) </strong> </td>
                            <td> TC Lauterbach 1973 </td>
                        </tr>
                        <tr>
                            <td align="right"> 14:00 </td>
                            <td> S1 </td>
                            <td> <strong> Herren 40 </strong> </td>
                            <td> TC Marxheim </td>
                        </tr>
                        <tr>
                            <td align="right"> 14:00 </td>
                            <td> S1 </td>
                            <td> <strong> Damen 50 (4er) </strong> </td>
                            <td> TSV Schondorf </td>
                        </tr>
                        <tr>
                            <td align="right"> 14:00 </td>
                            <td> LL2 </td>
                            <td> TSV Harburg </td>
                            <td> <strong> Herren 50 </strong> </td>
                        </tr>
                        <tr>
                            <td align="right"> So. 25.06.2023 09:00 </td>
                            <td> S4 </td>
                            <td> <strong> Herren </strong> </td>
                            <td> TC Gernlinden IV </td>
                        </tr>
                        <tr>
                            <td align="right"> 09:00 </td>
                            <td> S3 </td>
                            <td> Münchner Sportclub III </td>
                            <td> <strong> Damen </strong> </td>
                        </tr>
                        <tr>
                            <td align="right"> 09:00 </td>
                            <td> S1 </td>
                            <td> TC Puchheim II </td>
                            <td> <strong> Herren 55 (5er) </strong> </td>
                        </tr>
                        <tr>
                            <td align="right"> 10:00 </td>
                            <td> LL2 </td>
                            <td> TC Grün-Weiß Gräfelfing </td>
                            <td> <strong> Damen 40 </strong> </td>
                        </tr>
                        <tr>
                            <td align="right"> 15:00 </td>
                            <td> S2 </td>
                            <td> <strong> Dunlop Midcourt U10 (4er) </strong> </td>
                            <td> TSV Indersdorf </td>
                        </tr>
                        <tr>
                            <td align="right"> Mo. 26.06.2023 10:00 </td>
                            <td> S1 </td>
                            <td> SC Oberweikertshofen </td>
                            <td> <strong> Freizeit-Damen Doppel 60 </strong> </td>
                        </tr>
                        <tr>
                            <td align="right"> Fr. 30.06.2023 15:00 </td>
                            <td> S5 </td>
                            <td> <strong> Knaben 15 (4er) </strong> </td>
                            <td> TSV Geiselbullach II </td>
                        </tr>
                        <tr>
                            <td align="right"> 15:00 </td>
                            <td> S3 </td>
                            <td> Münchner Sportclub II </td>
                            <td> <strong> Mädchen 15 (4er) </strong> </td>
                        </tr>
                        <tr>
                            <td align="right"> Sa. 01.07.2023 09:00 </td>
                            <td> S3 </td>
                            <td> <strong> Junioren 18 (4er) </strong> </td>
                            <td> TC Mammendorf </td>
                        </tr>
                        <tr>
                            <td align="right"> 09:00 </td>
                            <td> S3 </td>
                            <td> TV Altomünster </td>
                            <td> <strong> Bambini 12 (4er) </strong> </td>
                        </tr>
                        <tr>
                            <td align="right"> 14:00 </td>
                            <td> LL2 </td>
                            <td> <strong> Damen 40 </strong> </td>
                            <td> DJK Würmtal München </td>
                        </tr>
                        <tr>
                            <td align="right"> 14:00 </td>
                            <td> S1 </td>
                            <td> TSV Königsbrunn </td>
                            <td> <strong> Herren 40 </strong> </td>
                        </tr>
                        <tr>
                            <td align="right"> 14:00 </td>
                            <td> S1 </td>
                            <td> TSV Gilching </td>
                            <td> <strong> Damen 50 (4er) </strong> </td>
                        </tr>
                        <tr>
                            <td align="right"> 14:00 </td>
                            <td> S3 </td>
                            <td> TSV Eintracht Karlsfeld III </td>
                            <td> <strong> Herren 50 II </strong> </td>
                        </tr>
                        <tr>
                            <td align="right"> 14:00 </td>
                            <td> S1 </td>
                            <td> <strong> Herren 55 (5er) </strong> </td>
                            <td> TC Eching </td>
                        </tr>
                        <tr>
                            <td align="right"> So. 02.07.2023 09:00 </td>
                            <td> S4 </td>
                            <td> <strong> Herren </strong> </td>
                            <td> TC Rot-Weiß Eschenried III </td>
                        </tr>
                        <tr>
                            <td align="right"> 09:00 </td>
                            <td> S4 </td>
                            <td> <strong> Herren 30 (4er) </strong> </td>
                            <td> FC Tandern </td>
                        </tr>
                        <tr>
                            <td align="right"> 15:00 </td>
                            <td> S2 </td>
                            <td> <strong> Dunlop Midcourt U10 (4er) </strong> </td>
                            <td> TC Dachau 1950 </td>
                        </tr>
                        <tr>
                            <td align="right"> Mo. 03.07.2023 10:00 </td>
                            <td> S1 </td>
                            <td> <strong> Freizeit-Damen Doppel 60 </strong> </td>
                            <td> TC Augsburg Siebentisch </td>
                        </tr>
                        <tr>
                            <td align="right"> Fr. 07.07.2023 15:00 </td>
                            <td> S5 </td>
                            <td> SV Sulzemoos II </td>
                            <td> <strong> Knaben 15 (4er) </strong> </td>
                        </tr>
                        <tr>
                            <td align="right"> Sa. 08.07.2023 09:00 </td>
                            <td> S3 </td>
                            <td> <strong> Junioren 18 (4er) </strong> </td>
                            <td> 1. SC Gröbenzell </td>
                        </tr>
                        <tr>
                            <td align="right"> 09:00 </td>
                            <td> S3 </td>
                            <td> ESV München Sportpark II </td>
                            <td> <strong> Bambini 12 (4er) </strong> </td>
                        </tr>
                        <tr>
                            <td align="right"> 14:00 </td>
                            <td> LL2 </td>
                            <td> TC Schießgraben Augsburg </td>
                            <td> <strong> Herren 50 </strong> </td>
                        </tr>
                        <tr>
                            <td align="right"> 14:00 </td>
                            <td> LL2 </td>
                            <td> <strong> Damen 40 </strong> </td>
                            <td> ASV Dachau </td>
                        </tr>
                        <tr>
                            <td align="right"> 14:00 </td>
                            <td> S1 </td>
                            <td> TeG Lech-Schmuttertal </td>
                            <td> <strong> Herren 40 </strong> </td>
                        </tr>
                        <tr>
                            <td align="right"> </td>
                            <td> 0 </td>
                            <td> Spielort: FC Langweid </td>
                            <td> 0 </td>
                        </tr>
                        <tr>
                            <td align="right"> 14:00 </td>
                            <td> S1 </td>
                            <td> <strong> Herren 55 (5er) </strong> </td>
                            <td> TC Eichenau </td>
                        </tr>
                        <tr>
                            <td align="right"> So. 09.07.2023 09:00 </td>
                            <td> S3 </td>
                            <td> <strong> Damen </strong> </td>
                            <td> TC Schwabing </td>
                        </tr>
                        <tr>
                            <td align="right"> 09:00 </td>
                            <td> S4 </td>
                            <td> <strong> Herren 30 (4er) </strong> </td>
                            <td> SV Sulzemoos </td>
                        </tr>
                        <tr>
                            <td align="right"> 14:00 </td>
                            <td> S3 </td>
                            <td> <strong> Herren 50 II </strong> </td>
                            <td> SV Bergheim </td>
                        </tr>
                        <tr>
                            <td align="right"> 15:00 </td>
                            <td> S2 </td>
                            <td> TSV Geiselbullach </td>
                            <td> <strong> Dunlop Midcourt U10 (4er) </strong> </td>
                        </tr>
                        <tr>
                            <td align="right"> Sa. 15.07.2023 09:00 </td>
                            <td> S3 </td>
                            <td> TC Schleißheim </td>
                            <td> <strong> Junioren 18 (4er) </strong> </td>
                        </tr>
                        <tr>
                            <td align="right"> 09:00 </td>
                            <td> S4 </td>
                            <td> TF Fürstenfeldbruck </td>
                            <td> <strong> Junioren 18 II (4er) </strong> </td>
                        </tr>
                        <tr>
                            <td align="right"> 09:00 </td>
                            <td> S3 </td>
                            <td> <strong> Bambini 12 (4er) </strong> </td>
                            <td> TC Eichenau II </td>
                        </tr>
                        <tr>
                            <td align="right"> 14:00 </td>
                            <td> LL2 </td>
                            <td> <strong> Herren 50 </strong> </td>
                            <td> DJK Augsburg-Lechhausen </td>
                        </tr>
                        <tr>
                            <td align="right"> 14:00 </td>
                            <td> LL2 </td>
                            <td> TC Weilheim </td>
                            <td> <strong> Damen 40 </strong> </td>
                        </tr>
                        <tr>
                            <td align="right"> 14:00 </td>
                            <td> S1 </td>
                            <td> <strong> Damen 50 (4er) </strong> </td>
                            <td> TC Inning </td>
                        </tr>
                        <tr>
                            <td align="right"> So. 16.07.2023 09:00 </td>
                            <td> S4 </td>
                            <td> TC Puchheim III </td>
                            <td> <strong> Herren </strong> </td>
                        </tr>
                        <tr>
                            <td align="right"> 09:00 </td>
                            <td> S1 </td>
                            <td> <strong> Herren 40 </strong> </td>
                            <td> TSV Zusmarshausen </td>
                        </tr>

                    </table>

                </article>
            </div>


        </div>
    </div>
</div>