<?php

/** @var yii\web\View $this */

$this->title = 'TC Olching Web';
?>

<div class="site-index">
    <div class="body-content">
        <div class="container">

            <div class="row">
                <article id="inhalt" class="col content-table">
                    <!-- Content Table generated by JavaScript -->
                </article>
            </div>

            <div class="row">
                <article id="Termine und Preise">
                    <h2>Training</h2>
                    <h3>Anfänger Kinder- und Jugendtraining:</h3>
                    <p>Mittwoch 15.00-16.00 Uhr Kinder 6-9 Jahre</p>
                    <p>Donnerstag 16.00-17.00 Uhr Kinder/Jugendliche ab 10 Jahre</p>

                    <ul>
                        <li>Termine 17.05, 24.05, 14.06, 21.06, 28.06, 5.7, 12.7, 19.7, 26.7 (mittwochs)</li>
                        <li>Termine 18.05, 25.05, 15.06, 22.06, 29.06, 6.7, 13.7, 20.7, 27.7 (donnerstags)</li>
                        <li>Wenn der Platz bei Regen unbespielbar ist, muss der Kurs an dem Tag entfallen</li>
                        <li>Mindestteilnehmer: 6 </li>
                        <li>Schläger und Material werden bei Bedarf zur Verfügung gestellt</li>
                        <li>Preis: 80,-€ inkl. Schnuppermitgliedschaft im Verein</li>
                        <li>Anmeldeschluss: 14.05.2023 (spätere Anmeldungen werden nur nach freier Kapazität berücksichtigt)</li>
                    </ul>

                    <h3>Erwachsene:</h3>

                    <p><strong>„Tennisplatzreife“</strong> (Anfänger). </p>
                    <ul>
                        <li>Ziel: Erste Grundlagen erlernen und am Ende spielen können.</li>
                    </ul>

                    <p><strong>„Comeback-Training“</strong> (für Spieler, die schon einmal gespielt haben)</p>
                    <ul>
                        <li>Ziel: Gelerntes auffrischen, um in der Freizeit wieder Tennis zu spielen </li>
                    </ul>

                    <h3>Samstags:</h3>
                    <ul>
                        <li>Termine: 13.05, 20.5, 17.06, 24.6, 01.7, 08.07, 15.07, 22.07, 29.07</li>
                        <li>Mindestteilnehmer pro Kurs: 4 </li>
                        <li>Schläger und Material werden bei Bedarf zur Verfügung gestellt</li>
                        <li>Preis: 100.-€ inkl. Schnuppermitgliedschaft im Verein</li>
                        <li>Anmeldeschluss: 10.05.2023 (spätere Anmeldungen werden nur nach freier Kapazität berücksichtigt)</li>
                    </ul>
                    <p><strong>Anmeldung oder Fragen bitte per E-Mail an: <a href="mailto:michael070985@icloud.com">Michael Görzen (michael070985@icloud.com)</a> </strong></p>
                </article>
            </div>

            <div class="row">
                <article id="trainer" class="col">
                    <h2>Michael Görzen: Unser Vereinstrainer</h2>
                    <h3>Liebe TCO'ler</h3>
                    <p>Ich bin beim TCO Trainer in Vollzeit und für die Trainerposition in 2020 nach Olching umgesiedelt.</p>
                    <p>Ich bin ehemaliger 2. Bundesligaspieler und habe in internationalen Turnieren gespielt.
                        Als Trainer arbeite ich seit 2001. Mein Ukraine-stämmiger Vater hat eine Tennisschule in Eching bei München.
                        Ich spreche Deutsch, Russisch, Englisch und etwas Französisch.</p>
                    </p>
                    <p><strong>Meine Kontaktdaten:</strong></p>
                    <p>Email: michael070985@icloud.com</p>
                    <p>WhatsApp: +49 179 5665353</p>
                    <p>Tel mobil: +49 176 74815404</p>
                    <p><strong>Gruppenpreise je Stunde:</strong></p>
                    <p>1 -2 Spieler: 44,00 EUR</p>
                    <p>3 Spieler: 45,00 EUR</p>
                    <p>4 Spieler: 48,00 EUR</p>
                </article>
                <div class="col">
                    <img alt="Trainer Michael Görzen" src="img/people/michael_goerzen_portrait.png" />
                </div>
            </div>

        </div>
    </div>
</div>

</div>

</div>