<?php

/** @var yii\web\View $this */

$this->title = 'TC Olching - Der Verein';
?>

<div class="site-index">
    <div class="body-content">
        <div class="container">

            <div class="row">
                <article id="inhalt" class="col content-table">
                    <!-- Content Table generated by JavaScript -->
                </article>
            </div>

            <!-- Mitgliedschaft Section -->
            <div class="row">
                <article class="col" id="mitgliedschaft">
                    <h2>Mitgliedsbeiträge</h2>
                    <table class="tco-table tco-tbl-small">
                        <thead>
                            <tr>
                                <th>Mitgliedschaft</th>
                                <th class="euro">Jahresbeitrag</th>
                                <th class="mittig">Reduzierung durch Arbeitseinsatz möglich</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>Kind bis 10 Jahre</td>
                                <td class="euro">35,00 EUR</td>
                                <td class="mittig">--</td>
                            </tr>
                            <tr>
                                <td>Kind bis 14 Jahre</td>
                                <td class="euro">55,00 EUR</td>
                                <td class="mittig">--</td>
                            </tr>
                            <tr>
                                <td>Jugendlicher bis 18 Jahre</td>
                                <td class="euro">85,00 EUR</td>
                                <td class="mittig">--</td>
                            </tr>
                            <tr>
                                <td>Azubis/Studenten bis 26 Jahre *</td>
                                <td class="euro">105,00 EUR</td>
                                <td class="mittig">--</td>
                            </tr>
                            <tr>
                                <td>Erwachsener</td>
                                <td class="euro">225,00 EUR </td>
                                <td class="mittig">✓</td>
                            </tr>
                            <tr>
                                <td>Ehepaar</td>
                                <td class="euro">380,00 EUR</td>
                                <td class="mittig">✓</td>
                            </tr>
                            <tr>
                                <td>Familie (Kinder bis 18 Jahre)</td>
                                <td class="euro">410,00 EUR</td>
                                <td class="mittig">✓</td>
                            </tr>
                            <tr>
                                <td>Kind mit vollzahlendem Elternteil</td>
                                <td class="euro">35,00 EUR</td>
                                <td class="mittig">--</td>
                            </tr>
                            <tr>
                                <td>Passiv</td>
                                <td class="euro">55,00 EUR</td>
                                <td class="mittig">--</td>
                            </tr>
                            <tr>
                                <td>Schnuppermitglied</td>
                                <td class="euro">55,00 EUR</td>
                                <td class="mittig">--</td>
                            </tr>
                        </tbody>
                    </table>
                    <p>* Um diese Beitragsermäßigung in Anspruch nehmen zu können, müssen die entsprechenden Bescheinigungen/Nachweise
                        selbstständig und rechtzeitig bis spätestens 31. Dezember eines jeden Jahres dem Verein vorliegen.
                        Nachträglich vorgelegte Bescheinigungen werden nicht rückwirkend berücksichtigt!
                    </p>
                    <p>** Die Schnuppermitgliedschaft kann nur einmal in Anspruch genommen werden und endet automatisch am 15. Juli.
                        Wird bis zu diesem Datum die reguläre Mitgliedschaft beantragt, kann bis zum Saisonende ohne Mehrkosten gespielt werden.
                    </p>
                    <h3>Hier gibt es den <strong><a href="downloads/TCO-Aufnahmeantrag2022.pdf">Aufnahmeantrag</a></strong>.</h3>
                </article>

            </div>
            <div class="row">

                <!-- Schnuppermitgliedschaft Section -->
                <article class="col" id="schnuppern">
                    <h2>Schnuppermitgliedschaft</h2>
                    <p>
                        Der TC Olching bietet auch dieses Jahr wieder allen Interessierten eine
                        Schnuppermitgliedschaft für 55 EUR.
                    </p>
                    <ul>
                        <li>Teilnahme am &#8222;Drop-In&#8220; (Mixed-Turnier zum Kennenlernen)
                            jeden Montag ab 18:00 Uhr</li>
                        <li>Spielberechtigung werktags bis 17:00 Uhr (nach 17:00 Uhr
                            nur bei Verfügbarkeit der Plätze &#8211; Mitglieder haben Vorrang!)</li>
                        <li>Spielberechtigung am Wochenende und an Feiertagen bei
                            Verfügbarkeit der Plätze</li>
                        <li>Ab Mitte Juli (nach Ende der Punktspielsaison)
                            Spielberechtigung wie jedes andere aktive Mitglied, wenn ein
                            Mitgliedsantrag für das Folgejahr vorliegt (siehe unten)</li>
                    </ul>
                    <p>
                        <strong>Die Schnuppermitgliedschaft kann nur einmal in Anspruch genommen werden und endet automatisch am 15. Juli.
                            Wird bis zu diesem Datum die reguläre Mitgliedschaft für das Folgejahr beantragt, kann bis zum Saisonende ohne Mehrkosten weitergespielt werden!</strong>
                    </p>
                    <p>Bei Interesse erreichst du uns telefonisch unter (08142) 667869, per E-Mail unter <a href="mailto:anmeldung@tcolching.de">anmeldung@tcolching.de</a>.
                        Während der Öffnungszeiten unseres Vereinsheimes kannst du auch gerne eine Nachricht bei unseren Wirtsleuten hinterlassen.
                    </p>
                    <h3>Hier gibt es den <strong><a href="downloads/TCO-Aufnahmeantrag2022.pdf">Aufnahmeantrag</a></strong>.</h3>
                </article>
            </div>
            <div class="row">

                <!-- Drop-In Section -->
                <article class="col" id="dropin">
                    <h2>Drop-In - jeden Montag ab 18:00 Uhr</h2>
                    <p>
                        Jeden Montag treffen sich alle, die Lust haben zum "Drop-In". Spielerinnen und Spieler werden zu alle 20 Minuten wechselnden Mixed-Paarungen zusammengelost. Danach sitzen wir gerne zusammen bei einem gemütlichen verdienten Bier oder einem Cocktail. Unsere Vereinsgaststätte ist bewirtet.
                    </p>
                    <p>
                        Die Teilnahme ist zum Kennenlernen auch für Nicht-Mitglieder zu einem symbolischen Beitrag von 1 EUR möglich.
                    </p>
                </article>
            </div>

            <div class="row">
                <!-- Vorstand Section -->

                <article class="col" id="vorstand">
                    <h2>Der Vorstand</h2>
                    <div class="visitenkarte">
                        <img alt="Conny Roloff" src="img/people/conny_roloff.png">
                        <div class="daten">1. Vorsitzender<br>Conny Roloff<br>
                            <a href="mailto:conny.roloff@tcolching.de">conny.roloff@tcolching.de</a>
                        </div>
                    </div>
                    <div class="visitenkarte">
                        <img alt="Michael Sachse" src="img/people/michael_sachse.png">
                        <div class="daten">2. Vorsitzender<br>
                            Michael Sachse<br>
                            <a href="mailto:michael.sachse@tcolching.de">michael.sachse@tcolching.de</a>
                        </div>
                    </div>
                    <div class="visitenkarte">
                        <img alt="Andrea Gallert" src="img/people/andrea_gallert.png">
                        <div class="daten">3. Vorsitzende, Kassenwartin<br>
                            Andrea Gallert<br>
                            <a href="mailto:andrea.gallert@tcolching.de">andrea.gallert@tcolching.de</a>
                        </div>
                    </div>
                    <div class="visitenkarte">
                        <img alt="Daniela Ulrich" src="img/people/daniela_ulrich.png">
                        <div class="daten">Schriftführerin<br>
                            Daniela Ulrich<br>
                            <a href="mailto:schriftführer@tcolching.de">schriftführer@tcolching.de</a>
                        </div>
                    </div>
                    <div class="visitenkarte">
                        <img alt="Thomas Schek" src="img/people/thomas_schek.png">
                        <div class="daten">Sportwart<br>Thomas Schek<br>
                            <a href="mailto:sportwart@tcolching.de">sportwart@tcolching.de</a>
                        </div>
                    </div>
                    <div class="visitenkarte">
                        <img alt="Heiko Tesche" src="img/people/heiko_tesche.png">
                        <div class="daten">Jugendwart<br>Heiko Tesche<br>
                            <a href="mailto:jugendwart@tcolching.de">jugendwart@tcolching.de</a>
                        </div>
                    </div>
                    <div class="visitenkarte">
                        <img alt="Thomas Stief" src="img/people/thomas_stief.png">
                        <div class="daten">Beisitzer Pressearbeit<br>
                            Thomas Stief<br>
                            <a href="mailto:presse@tcolching.de">presse@tcolching.de</a>
                        </div>
                    </div>
                    <div class="visitenkarte">
                        <img alt="Lisa Fuchs" src="img/people/lisa_fuchs.png">
                        <div class="daten">Beisitzerin<br>
                            Lisa Fuchs<br>
                            <a href="mailto:lisa.fuchs@tcolching.de">lisa.fuchs@tcolching.de</a>
                        </div>
                    </div>
                </article>
            </div>

            <div class="row">

                <!-- Unterstützung Section -->
                <article class="col" id="unterstuetzung">
                    <h2>Unterstützung des TC Olching</h2>
                    <p>
                        Als Verein hat der TC Olching keinerlei Gewinnerzielungsabsichten.
                        Da jedoch der Betrieb eines Tennisvereins kostenintensiv ist, freuen wir uns über jegliche Unterstützung.
                    </p>
                    <h3>Freiwilliges Engagement</h3>
                    <p>
                        Zu allererst ist hier natürlich das freiwillige Engagement all jener zu nennen, die in ihrer Freizeit Clubleben,
                        Anlage, sportliche und gesellschaftliche Ereignisse sowie die Jugenbetreuung organiseren und am Laufen halten.
                        Am offensichtlichsten ist dies bei unserer Vorstandsschaft. Aber genau so sind hier die zahlreichen
                        freiwilligen Helfer verschiedener Anlässe zu nennen, sei es bei den Olching Open, bei Platzinstandsetzung oder
                        Renovierung oder auch nur die kleine Handreichung beim DropIn.
                        All dies zeugt von einem intakten Clubleben und ist durchaus etwas, auf das wir alle stolz sein können.
                        Wer sich engagieren will, Michi weiß immer was zu tun ist: <a href="mailto:michael.sachse@tcolching.de">michael.sachse@tcolching.de</a>.
                    </p>
                    <h3>Sponsoren</h3>
                    <p>
                        Darüberhinaus sind wir natürlich immer wieder auf finanzielle Zuwendungen angewiesen.
                        Auf der Startseite unseres Webauftrittes siehst du z. B. unsere Jugendsponsoren,
                        die jeweils 50,00 € für die Jugendarbeit gespendet haben.
                    </p>
                    <p>
                        Vielen Dank hierfür!
                    </p>
                    <p>
                        Wer hieran noch Interesse hätte, kurze Mail an <a href="mailto:jugendwart@tcolching.de">jugendwart@tcolching.de</a> genügt.
                    </p>
                    <h3>Olching Open</h3>
                    <p>
                        Ein Turnier, bei dem Spieler, die niedrige 3-stellige Weltranglistenpositionen belegen, auftreten, ist ohne finanzielle Zuwendungen seitens
                        Dritter für den TCO nicht zu stemmen. Für die diesjährigen Olching Open würden wir noch dringend Spendengelder benötigen.
                        Wir gehen davon aus, dass die Erwähnung als Sponsor in Ausschreibung, im hiesigen Webauftritt, sowie auf der Anlage für jeden
                        Gewerbebetrieb durchaus einen ernstzunehmenden Imagegewinn darstellt sowie den Bekanntheitsgrad steigert. Ansprechpartner
                        hierfür ist Heiko Tesche: <a href="mailto:heiko.tesche@tcolching.de">heiko.tesche@tcolching.de</a>.
                    </p>
                    <h3>5% für den TCO</h3>
                    <p>
                        Eine ganz neue Art der Zuwendung bietet sich über den Kauf von Tennisschlägern, -Schuhen, -Bekleidung und -Zubehör.
                        Der Onlinehändler Tennisplanet.de vergütet dem TCO jede Bestellung über den untenstehenden Banner mit 5%.
                    </p>
                </article>
            </div>
            <div class="row">
                <!-- Übernachtungsmöglichkeiten Section -->
                <article class="col mt-7" id="uebernachtung">
                    <div class="row">
                        <div class="col">
                            <h2>Übernachtungsmöglichkeiten in Olching</h2>
                        </div>
                        <div class="mb-5">
                            <strong>
                                Anfragen an den TCO: <a href="mailto:mail@tcolching.de">mail@tcolching.de</a>.
                            </strong>
                        </div>
                        <div>
                            <h3>Hotel Schiller</h3>
                            <p>
                                Nöscherstr. 20<br>
                                82140 Olching<br>
                                Tel.: 08142/4730<br>
                            </p>
                        </div>
                        <div>
                            <h3>Hotel am Krone Park</h3>
                            <p>
                                Kemeterstrasse 55<br>
                                82140 Olching<br>
                                Tel.: 08142/2920<br>
                            </p>
                        </div>
                        <div>
                            <h3>Berner Lilo</h3>
                            <p>
                                Prof.-Schmid-Str. 25<br>
                                82140 Olching<br>
                                Tel.: 08142/3251<br>
                            </p>
                        </div>
                        <div>
                            <h3>Campingplatz Sägmühle</h3>
                            <p>
                                Sägmühlstr. 25<br>
                                82140 Olching<br>
                                Tel.: 08142/443038
                            </p>
                        </div>
                    </div>
                </article>
                <div class="col mt-5">
                    <img class="img-fluid mb-3" src="img/misc/uebernachtungen.png" alt="Übernachtungen">
                </div>
            </div>

            <div class="row">
                <!-- Dokumente Section -->
                <article class="col" id="dokumente">
                    <h2>Downloads</h2>
                    <h3>Satzung, Gastspielordnung, Platzordnung und mehr zum Download</h3>
                    <ul>
                        <li><a href="downloads/Satzung_TCO.pdf">Satzung</a></li>
                        <li><a href="downloads/Gastspielordnung_2021.pdf">Gastspielordnung</a></li>
                        <li><a href="downloads/Platzordnung_2021.pdf">Platzordnung</a></li>
                        <li><a href="downloads/TCO-Aufnahmeantrag2022.pdf">Aufnahmeantrag</a></li>
                    </ul>
                </article>
            </div>

            <div class="row">
                <!-- Anfahrt Section -->
                <article class="col mx-0" id="anfahrt">
                    <h2>Anfahrt</h2>
                    <iframe id="googlekarte" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2658.8147746398376!2d11.323605951557064!3d48.21018355397781!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x479e7efa9005591b%3A0x2115bcb26790403c!2sTennisclub+Olching+e.V.!5e0!3m2!1sde!2sde!4v1464081688508" allowfullscreen></iframe>
                </article>
            </div>

        </div>
    </div>
</div>